<?php
namespace Database\Seeders;

use App\Models\Lga;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LgasTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('lgas')->delete();

        // Indian districts mapped to state IDs (1-36 as per states seeder)
        $districts = [
            // Andhra Pradesh (state_id: 1)
            ['state_id' => 1, 'name' => 'Anantapur'],
            ['state_id' => 1, 'name' => 'Chittoor'],
            ['state_id' => 1, 'name' => 'East Godavari'],
            ['state_id' => 1, 'name' => 'Guntur'],
            ['state_id' => 1, 'name' => 'Krishna'],
            ['state_id' => 1, 'name' => 'Kurnool'],
            ['state_id' => 1, 'name' => 'Nellore'],
            ['state_id' => 1, 'name' => 'Prakasam'],
            ['state_id' => 1, 'name' => 'Srikakulam'],
            ['state_id' => 1, 'name' => 'Visakhapatnam'],
            ['state_id' => 1, 'name' => 'Vizianagaram'],
            ['state_id' => 1, 'name' => 'West Godavari'],
            ['state_id' => 1, 'name' => 'Kadapa'],

            // Arunachal Pradesh (state_id: 2)
            ['state_id' => 2, 'name' => 'Anjaw'],
            ['state_id' => 2, 'name' => 'Changlang'],
            ['state_id' => 2, 'name' => 'Dibang Valley'],
            ['state_id' => 2, 'name' => 'East Kameng'],
            ['state_id' => 2, 'name' => 'East Siang'],
            ['state_id' => 2, 'name' => 'Kamle'],
            ['state_id' => 2, 'name' => 'Kra Daadi'],
            ['state_id' => 2, 'name' => 'Kurung Kumey'],
            ['state_id' => 2, 'name' => 'Lepa Rada'],
            ['state_id' => 2, 'name' => 'Lohit'],
            ['state_id' => 2, 'name' => 'Longding'],
            ['state_id' => 2, 'name' => 'Lower Dibang Valley'],
            ['state_id' => 2, 'name' => 'Lower Siang'],
            ['state_id' => 2, 'name' => 'Lower Subansiri'],
            ['state_id' => 2, 'name' => 'Namsai'],
            ['state_id' => 2, 'name' => 'Pakke Kessang'],
            ['state_id' => 2, 'name' => 'Papumpare'],
            ['state_id' => 2, 'name' => 'Shi Yomi'],
            ['state_id' => 2, 'name' => 'Siang'],
            ['state_id' => 2, 'name' => 'Tawang'],
            ['state_id' => 2, 'name' => 'Tirap'],
            ['state_id' => 2, 'name' => 'Upper Siang'],
            ['state_id' => 2, 'name' => 'Upper Subansiri'],
            ['state_id' => 2, 'name' => 'West Kameng'],
            ['state_id' => 2, 'name' => 'West Siang'],

            // Assam (state_id: 3)
            ['state_id' => 3, 'name' => 'Baksa'],
            ['state_id' => 3, 'name' => 'Barpeta'],
            ['state_id' => 3, 'name' => 'Biswanath'],
            ['state_id' => 3, 'name' => 'Bongaigaon'],
            ['state_id' => 3, 'name' => 'Cachar'],
            ['state_id' => 3, 'name' => 'Charaideo'],
            ['state_id' => 3, 'name' => 'Chirang'],
            ['state_id' => 3, 'name' => 'Darrang'],
            ['state_id' => 3, 'name' => 'Dhemaji'],
            ['state_id' => 3, 'name' => 'Dhubri'],
            ['state_id' => 3, 'name' => 'Dibrugarh'],
            ['state_id' => 3, 'name' => 'Goalpara'],
            ['state_id' => 3, 'name' => 'Golaghat'],
            ['state_id' => 3, 'name' => 'Hailakandi'],
            ['state_id' => 3, 'name' => 'Hojai'],
            ['state_id' => 3, 'name' => 'Jorhat'],
            ['state_id' => 3, 'name' => 'Kamrup'],
            ['state_id' => 3, 'name' => 'Kamrup Metropolitan'],
            ['state_id' => 3, 'name' => 'Karbi Anglong'],
            ['state_id' => 3, 'name' => 'Karimganj'],
            ['state_id' => 3, 'name' => 'Kokrajhar'],
            ['state_id' => 3, 'name' => 'Lakhimpur'],
            ['state_id' => 3, 'name' => 'Majuli'],
            ['state_id' => 3, 'name' => 'Morigaon'],
            ['state_id' => 3, 'name' => 'Nagaon'],
            ['state_id' => 3, 'name' => 'Nalbari'],
            ['state_id' => 3, 'name' => 'Dima Hasao'],
            ['state_id' => 3, 'name' => 'Sivasagar'],
            ['state_id' => 3, 'name' => 'Sonitpur'],
            ['state_id' => 3, 'name' => 'South Salmara-Mankachar'],
            ['state_id' => 3, 'name' => 'Tinsukia'],
            ['state_id' => 3, 'name' => 'Udalguri'],
            ['state_id' => 3, 'name' => 'West Karbi Anglong'],

            // Bihar (state_id: 4)
            ['state_id' => 4, 'name' => 'Araria'],
            ['state_id' => 4, 'name' => 'Arwal'],
            ['state_id' => 4, 'name' => 'Aurangabad'],
            ['state_id' => 4, 'name' => 'Banka'],
            ['state_id' => 4, 'name' => 'Begusarai'],
            ['state_id' => 4, 'name' => 'Bhagalpur'],
            ['state_id' => 4, 'name' => 'Bhojpur'],
            ['state_id' => 4, 'name' => 'Buxar'],
            ['state_id' => 4, 'name' => 'Darbhanga'],
            ['state_id' => 4, 'name' => 'East Champaran'],
            ['state_id' => 4, 'name' => 'Gaya'],
            ['state_id' => 4, 'name' => 'Gopalganj'],
            ['state_id' => 4, 'name' => 'Jamui'],
            ['state_id' => 4, 'name' => 'Jehanabad'],
            ['state_id' => 4, 'name' => 'Kaimur'],
            ['state_id' => 4, 'name' => 'Katihar'],
            ['state_id' => 4, 'name' => 'Khagaria'],
            ['state_id' => 4, 'name' => 'Kishanganj'],
            ['state_id' => 4, 'name' => 'Lakhisarai'],
            ['state_id' => 4, 'name' => 'Madhepura'],
            ['state_id' => 4, 'name' => 'Madhubani'],
            ['state_id' => 4, 'name' => 'Munger'],
            ['state_id' => 4, 'name' => 'Muzaffarpur'],
            ['state_id' => 4, 'name' => 'Nalanda'],
            ['state_id' => 4, 'name' => 'Nawada'],
            ['state_id' => 4, 'name' => 'Patna'],
            ['state_id' => 4, 'name' => 'Purnia'],
            ['state_id' => 4, 'name' => 'Rohtas'],
            ['state_id' => 4, 'name' => 'Saharsa'],
            ['state_id' => 4, 'name' => 'Samastipur'],
            ['state_id' => 4, 'name' => 'Saran'],
            ['state_id' => 4, 'name' => 'Sheikhpura'],
            ['state_id' => 4, 'name' => 'Sheohar'],
            ['state_id' => 4, 'name' => 'Sitamarhi'],
            ['state_id' => 4, 'name' => 'Siwan'],
            ['state_id' => 4, 'name' => 'Supaul'],
            ['state_id' => 4, 'name' => 'Vaishali'],
            ['state_id' => 4, 'name' => 'West Champaran'],

            // Chhattisgarh (state_id: 5)
            ['state_id' => 5, 'name' => 'Balod'],
            ['state_id' => 5, 'name' => 'Baloda Bazar'],
            ['state_id' => 5, 'name' => 'Balrampur'],
            ['state_id' => 5, 'name' => 'Bastar'],
            ['state_id' => 5, 'name' => 'Bemetara'],
            ['state_id' => 5, 'name' => 'Bijapur'],
            ['state_id' => 5, 'name' => 'Bilaspur'],
            ['state_id' => 5, 'name' => 'Dantewada'],
            ['state_id' => 5, 'name' => 'Dhamtari'],
            ['state_id' => 5, 'name' => 'Durg'],
            ['state_id' => 5, 'name' => 'Gariaband'],
            ['state_id' => 5, 'name' => 'Gaurela Pendra Marwahi'],
            ['state_id' => 5, 'name' => 'Janjgir Champa'],
            ['state_id' => 5, 'name' => 'Jashpur'],
            ['state_id' => 5, 'name' => 'Kabirdham'],
            ['state_id' => 5, 'name' => 'Kanker'],
            ['state_id' => 5, 'name' => 'Kondagaon'],
            ['state_id' => 5, 'name' => 'Korba'],
            ['state_id' => 5, 'name' => 'Koriya'],
            ['state_id' => 5, 'name' => 'Mahasamund'],
            ['state_id' => 5, 'name' => 'Mungeli'],
            ['state_id' => 5, 'name' => 'Narayanpur'],
            ['state_id' => 5, 'name' => 'Raigarh'],
            ['state_id' => 5, 'name' => 'Raipur'],
            ['state_id' => 5, 'name' => 'Rajnandgaon'],
            ['state_id' => 5, 'name' => 'Sukma'],
            ['state_id' => 5, 'name' => 'Surajpur'],
            ['state_id' => 5, 'name' => 'Surguja'],

            // Goa (state_id: 6)
            ['state_id' => 6, 'name' => 'North Goa'],
            ['state_id' => 6, 'name' => 'South Goa'],

            // Gujarat (state_id: 7)
            ['state_id' => 7, 'name' => 'Ahmedabad'],
            ['state_id' => 7, 'name' => 'Amreli'],
            ['state_id' => 7, 'name' => 'Anand'],
            ['state_id' => 7, 'name' => 'Aravalli'],
            ['state_id' => 7, 'name' => 'Banaskantha'],
            ['state_id' => 7, 'name' => 'Bharuch'],
            ['state_id' => 7, 'name' => 'Bhavnagar'],
            ['state_id' => 7, 'name' => 'Botad'],
            ['state_id' => 7, 'name' => 'Chhota Udaipur'],
            ['state_id' => 7, 'name' => 'Dahod'],
            ['state_id' => 7, 'name' => 'Dang'],
            ['state_id' => 7, 'name' => 'Devbhoomi Dwarka'],
            ['state_id' => 7, 'name' => 'Gandhinagar'],
            ['state_id' => 7, 'name' => 'Gir Somnath'],
            ['state_id' => 7, 'name' => 'Jamnagar'],
            ['state_id' => 7, 'name' => 'Junagadh'],
            ['state_id' => 7, 'name' => 'Kheda'],
            ['state_id' => 7, 'name' => 'Kutch'],
            ['state_id' => 7, 'name' => 'Mahisagar'],
            ['state_id' => 7, 'name' => 'Mehsana'],
            ['state_id' => 7, 'name' => 'Morbi'],
            ['state_id' => 7, 'name' => 'Narmada'],
            ['state_id' => 7, 'name' => 'Navsari'],
            ['state_id' => 7, 'name' => 'Panchmahal'],
            ['state_id' => 7, 'name' => 'Patan'],
            ['state_id' => 7, 'name' => 'Porbandar'],
            ['state_id' => 7, 'name' => 'Rajkot'],
            ['state_id' => 7, 'name' => 'Sabarkantha'],
            ['state_id' => 7, 'name' => 'Surat'],
            ['state_id' => 7, 'name' => 'Surendranagar'],
            ['state_id' => 7, 'name' => 'Tapi'],
            ['state_id' => 7, 'name' => 'Vadodara'],
            ['state_id' => 7, 'name' => 'Valsad'],

            // Continue with remaining states...
            // For brevity, I'll add a few more key states

            // Delhi (state_id: 32)
            ['state_id' => 32, 'name' => 'Central Delhi'],
            ['state_id' => 32, 'name' => 'East Delhi'],
            ['state_id' => 32, 'name' => 'New Delhi'],
            ['state_id' => 32, 'name' => 'North Delhi'],
            ['state_id' => 32, 'name' => 'North East Delhi'],
            ['state_id' => 32, 'name' => 'North West Delhi'],
            ['state_id' => 32, 'name' => 'Shahdara'],
            ['state_id' => 32, 'name' => 'South Delhi'],
            ['state_id' => 32, 'name' => 'South East Delhi'],
            ['state_id' => 32, 'name' => 'South West Delhi'],
            ['state_id' => 32, 'name' => 'West Delhi'],

            // Maharashtra (state_id: 14)
            ['state_id' => 14, 'name' => 'Ahmednagar'],
            ['state_id' => 14, 'name' => 'Akola'],
            ['state_id' => 14, 'name' => 'Amravati'],
            ['state_id' => 14, 'name' => 'Aurangabad'],
            ['state_id' => 14, 'name' => 'Beed'],
            ['state_id' => 14, 'name' => 'Bhandara'],
            ['state_id' => 14, 'name' => 'Buldhana'],
            ['state_id' => 14, 'name' => 'Chandrapur'],
            ['state_id' => 14, 'name' => 'Dhule'],
            ['state_id' => 14, 'name' => 'Gadchiroli'],
            ['state_id' => 14, 'name' => 'Gondia'],
            ['state_id' => 14, 'name' => 'Hingoli'],
            ['state_id' => 14, 'name' => 'Jalgaon'],
            ['state_id' => 14, 'name' => 'Jalna'],
            ['state_id' => 14, 'name' => 'Kolhapur'],
            ['state_id' => 14, 'name' => 'Latur'],
            ['state_id' => 14, 'name' => 'Mumbai City'],
            ['state_id' => 14, 'name' => 'Mumbai Suburban'],
            ['state_id' => 14, 'name' => 'Nagpur'],
            ['state_id' => 14, 'name' => 'Nanded'],
            ['state_id' => 14, 'name' => 'Nandurbar'],
            ['state_id' => 14, 'name' => 'Nashik'],
            ['state_id' => 14, 'name' => 'Osmanabad'],
            ['state_id' => 14, 'name' => 'Palghar'],
            ['state_id' => 14, 'name' => 'Parbhani'],
            ['state_id' => 14, 'name' => 'Pune'],
            ['state_id' => 14, 'name' => 'Raigad'],
            ['state_id' => 14, 'name' => 'Ratnagiri'],
            ['state_id' => 14, 'name' => 'Sangli'],
            ['state_id' => 14, 'name' => 'Satara'],
            ['state_id' => 14, 'name' => 'Sindhudurg'],
            ['state_id' => 14, 'name' => 'Solapur'],
            ['state_id' => 14, 'name' => 'Thane'],
            ['state_id' => 14, 'name' => 'Wardha'],
            ['state_id' => 14, 'name' => 'Washim'],
            ['state_id' => 14, 'name' => 'Yavatmal']
        ];

        foreach ($districts as $district) {
            Lga::create($district);
        }
    }
}
