<?php

namespace Database\Seeders;

use App\Models\Lga;
use Illuminate\Database\Seeder;

class LgasTableSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $lgas = [
            // Andhra Pradesh (state_id: 1)
            ['state_id' => 1, 'name' => 'Anantapur'],
            ['state_id' => 1, 'name' => 'Chittoor'],
            ['state_id' => 1, 'name' => 'East Godavari'],
            ['state_id' => 1, 'name' => 'Guntur'],
            ['state_id' => 1, 'name' => 'Krishna'],
            ['state_id' => 1, 'name' => 'Kurnool'],
            ['state_id' => 1, 'name' => 'Nellore'],
            ['state_id' => 1, 'name' => 'Prakasam'],
            ['state_id' => 1, 'name' => 'Srikakulam'],
            ['state_id' => 1, 'name' => 'Visakhapatnam'],
            ['state_id' => 1, 'name' => 'Vizianagaram'],
            ['state_id' => 1, 'name' => 'West Godavari'],
            ['state_id' => 1, 'name' => 'YSR Kadapa'],

            // Arunachal Pradesh (state_id: 2)
            ['state_id' => 2, 'name' => 'Anjaw'],
            ['state_id' => 2, 'name' => 'Changlang'],
            ['state_id' => 2, 'name' => 'Dibang Valley'],
            ['state_id' => 2, 'name' => 'East Kameng'],
            ['state_id' => 2, 'name' => 'East Siang'],
            ['state_id' => 2, 'name' => 'Kamle'],
            ['state_id' => 2, 'name' => 'Kra Daadi'],
            ['state_id' => 2, 'name' => 'Kurung Kumey'],
            ['state_id' => 2, 'name' => 'Lepa Rada'],
            ['state_id' => 2, 'name' => 'Lohit'],
            ['state_id' => 2, 'name' => 'Longding'],
            ['state_id' => 2, 'name' => 'Lower Dibang Valley'],
            ['state_id' => 2, 'name' => 'Lower Siang'],
            ['state_id' => 2, 'name' => 'Lower Subansiri'],
            ['state_id' => 2, 'name' => 'Namsai'],
            ['state_id' => 2, 'name' => 'Pakke Kessang'],
            ['state_id' => 2, 'name' => 'Papum Pare'],
            ['state_id' => 2, 'name' => 'Shi Yomi'],
            ['state_id' => 2, 'name' => 'Siang'],
            ['state_id' => 2, 'name' => 'Tawang'],
            ['state_id' => 2, 'name' => 'Tirap'],
            ['state_id' => 2, 'name' => 'Upper Siang'],
            ['state_id' => 2, 'name' => 'Upper Subansiri'],
            ['state_id' => 2, 'name' => 'West Kameng'],
            ['state_id' => 2, 'name' => 'West Siang'],

            // Assam (state_id: 3)
            ['state_id' => 3, 'name' => 'Baksa'],
            ['state_id' => 3, 'name' => 'Barpeta'],
            ['state_id' => 3, 'name' => 'Biswanath'],
            ['state_id' => 3, 'name' => 'Bongaigaon'],
            ['state_id' => 3, 'name' => 'Cachar'],
            ['state_id' => 3, 'name' => 'Charaideo'],
            ['state_id' => 3, 'name' => 'Chirang'],
            ['state_id' => 3, 'name' => 'Darrang'],
            ['state_id' => 3, 'name' => 'Dhemaji'],
            ['state_id' => 3, 'name' => 'Dhubri'],
            ['state_id' => 3, 'name' => 'Dibrugarh'],
            ['state_id' => 3, 'name' => 'Goalpara'],
            ['state_id' => 3, 'name' => 'Golaghat'],
            ['state_id' => 3, 'name' => 'Hailakandi'],
            ['state_id' => 3, 'name' => 'Hojai'],
            ['state_id' => 3, 'name' => 'Jorhat'],
            ['state_id' => 3, 'name' => 'Kamrup'],
            ['state_id' => 3, 'name' => 'Kamrup Metropolitan'],
            ['state_id' => 3, 'name' => 'Karbi Anglong'],
            ['state_id' => 3, 'name' => 'Karimganj'],
            ['state_id' => 3, 'name' => 'Kokrajhar'],
            ['state_id' => 3, 'name' => 'Lakhimpur'],
            ['state_id' => 3, 'name' => 'Majuli'],
            ['state_id' => 3, 'name' => 'Morigaon'],
            ['state_id' => 3, 'name' => 'Nagaon'],
            ['state_id' => 3, 'name' => 'Nalbari'],
            ['state_id' => 3, 'name' => 'Dima Hasao'],
            ['state_id' => 3, 'name' => 'Sivasagar'],
            ['state_id' => 3, 'name' => 'Sonitpur'],
            ['state_id' => 3, 'name' => 'South Salmara-Mankachar'],
            ['state_id' => 3, 'name' => 'Tinsukia'],
            ['state_id' => 3, 'name' => 'Udalguri'],
            ['state_id' => 3, 'name' => 'West Karbi Anglong'],

            // Bihar (state_id: 4)
            ['state_id' => 4, 'name' => 'Araria'],
            ['state_id' => 4, 'name' => 'Arwal'],
            ['state_id' => 4, 'name' => 'Aurangabad'],
            ['state_id' => 4, 'name' => 'Banka'],
            ['state_id' => 4, 'name' => 'Begusarai'],
            ['state_id' => 4, 'name' => 'Bhagalpur'],
            ['state_id' => 4, 'name' => 'Bhojpur'],
            ['state_id' => 4, 'name' => 'Buxar'],
            ['state_id' => 4, 'name' => 'Darbhanga'],
            ['state_id' => 4, 'name' => 'East Champaran'],
            ['state_id' => 4, 'name' => 'Gaya'],
            ['state_id' => 4, 'name' => 'Gopalganj'],
            ['state_id' => 4, 'name' => 'Jamui'],
            ['state_id' => 4, 'name' => 'Jehanabad'],
            ['state_id' => 4, 'name' => 'Kaimur'],
            ['state_id' => 4, 'name' => 'Katihar'],
            ['state_id' => 4, 'name' => 'Khagaria'],
            ['state_id' => 4, 'name' => 'Kishanganj'],
            ['state_id' => 4, 'name' => 'Lakhisarai'],
            ['state_id' => 4, 'name' => 'Madhepura'],
            ['state_id' => 4, 'name' => 'Madhubani'],
            ['state_id' => 4, 'name' => 'Munger'],
            ['state_id' => 4, 'name' => 'Muzaffarpur'],
            ['state_id' => 4, 'name' => 'Nalanda'],
            ['state_id' => 4, 'name' => 'Nawada'],
            ['state_id' => 4, 'name' => 'Patna'],
            ['state_id' => 4, 'name' => 'Purnia'],
            ['state_id' => 4, 'name' => 'Rohtas'],
            ['state_id' => 4, 'name' => 'Saharsa'],
            ['state_id' => 4, 'name' => 'Samastipur'],
            ['state_id' => 4, 'name' => 'Saran'],
            ['state_id' => 4, 'name' => 'Sheikhpura'],
            ['state_id' => 4, 'name' => 'Sheohar'],
            ['state_id' => 4, 'name' => 'Sitamarhi'],
            ['state_id' => 4, 'name' => 'Siwan'],
            ['state_id' => 4, 'name' => 'Supaul'],
            ['state_id' => 4, 'name' => 'Vaishali'],
            ['state_id' => 4, 'name' => 'West Champaran'],

            // Chhattisgarh (state_id: 5)
            ['state_id' => 5, 'name' => 'Balod'],
            ['state_id' => 5, 'name' => 'Baloda Bazar'],
            ['state_id' => 5, 'name' => 'Balrampur'],
            ['state_id' => 5, 'name' => 'Bastar'],
            ['state_id' => 5, 'name' => 'Bemetara'],
            ['state_id' => 5, 'name' => 'Bijapur'],
            ['state_id' => 5, 'name' => 'Bilaspur'],
            ['state_id' => 5, 'name' => 'Dantewada'],
            ['state_id' => 5, 'name' => 'Dhamtari'],
            ['state_id' => 5, 'name' => 'Durg'],
            ['state_id' => 5, 'name' => 'Gariaband'],
            ['state_id' => 5, 'name' => 'Gaurela Pendra Marwahi'],
            ['state_id' => 5, 'name' => 'Janjgir Champa'],
            ['state_id' => 5, 'name' => 'Jashpur'],
            ['state_id' => 5, 'name' => 'Kabirdham'],
            ['state_id' => 5, 'name' => 'Kanker'],
            ['state_id' => 5, 'name' => 'Kondagaon'],
            ['state_id' => 5, 'name' => 'Korba'],
            ['state_id' => 5, 'name' => 'Koriya'],
            ['state_id' => 5, 'name' => 'Mahasamund'],
            ['state_id' => 5, 'name' => 'Mungeli'],
            ['state_id' => 5, 'name' => 'Narayanpur'],
            ['state_id' => 5, 'name' => 'Raigarh'],
            ['state_id' => 5, 'name' => 'Raipur'],
            ['state_id' => 5, 'name' => 'Rajnandgaon'],
            ['state_id' => 5, 'name' => 'Sukma'],
            ['state_id' => 5, 'name' => 'Surajpur'],
            ['state_id' => 5, 'name' => 'Surguja'],

            // Goa (state_id: 6)
            ['state_id' => 6, 'name' => 'North Goa'],
            ['state_id' => 6, 'name' => 'South Goa'],

            // Gujarat (state_id: 7)
            ['state_id' => 7, 'name' => 'Ahmedabad'],
            ['state_id' => 7, 'name' => 'Amreli'],
            ['state_id' => 7, 'name' => 'Anand'],
            ['state_id' => 7, 'name' => 'Aravalli'],
            ['state_id' => 7, 'name' => 'Banaskantha'],
            ['state_id' => 7, 'name' => 'Bharuch'],
            ['state_id' => 7, 'name' => 'Bhavnagar'],
            ['state_id' => 7, 'name' => 'Botad'],
            ['state_id' => 7, 'name' => 'Chhota Udaipur'],
            ['state_id' => 7, 'name' => 'Dahod'],
            ['state_id' => 7, 'name' => 'Dang'],
            ['state_id' => 7, 'name' => 'Devbhoomi Dwarka'],
            ['state_id' => 7, 'name' => 'Gandhinagar'],
            ['state_id' => 7, 'name' => 'Gir Somnath'],
            ['state_id' => 7, 'name' => 'Jamnagar'],
            ['state_id' => 7, 'name' => 'Junagadh'],
            ['state_id' => 7, 'name' => 'Kutch'],
            ['state_id' => 7, 'name' => 'Kheda'],
            ['state_id' => 7, 'name' => 'Mahisagar'],
            ['state_id' => 7, 'name' => 'Mehsana'],
            ['state_id' => 7, 'name' => 'Morbi'],
            ['state_id' => 7, 'name' => 'Narmada'],
            ['state_id' => 7, 'name' => 'Navsari'],
            ['state_id' => 7, 'name' => 'Panchmahal'],
            ['state_id' => 7, 'name' => 'Patan'],
            ['state_id' => 7, 'name' => 'Porbandar'],
            ['state_id' => 7, 'name' => 'Rajkot'],
            ['state_id' => 7, 'name' => 'Sabarkantha'],
            ['state_id' => 7, 'name' => 'Surat'],
            ['state_id' => 7, 'name' => 'Surendranagar'],
            ['state_id' => 7, 'name' => 'Tapi'],
            ['state_id' => 7, 'name' => 'Vadodara'],
            ['state_id' => 7, 'name' => 'Valsad'],

            // Haryana (state_id: 8)
            ['state_id' => 8, 'name' => 'Ambala'],
            ['state_id' => 8, 'name' => 'Bhiwani'],
            ['state_id' => 8, 'name' => 'Charkhi Dadri'],
            ['state_id' => 8, 'name' => 'Faridabad'],
            ['state_id' => 8, 'name' => 'Fatehabad'],
            ['state_id' => 8, 'name' => 'Gurugram'],
            ['state_id' => 8, 'name' => 'Hisar'],
            ['state_id' => 8, 'name' => 'Jhajjar'],
            ['state_id' => 8, 'name' => 'Jind'],
            ['state_id' => 8, 'name' => 'Kaithal'],
            ['state_id' => 8, 'name' => 'Karnal'],
            ['state_id' => 8, 'name' => 'Kurukshetra'],
            ['state_id' => 8, 'name' => 'Mahendragarh'],
            ['state_id' => 8, 'name' => 'Mewat'],
            ['state_id' => 8, 'name' => 'Palwal'],
            ['state_id' => 8, 'name' => 'Panchkula'],
            ['state_id' => 8, 'name' => 'Panipat'],
            ['state_id' => 8, 'name' => 'Rewari'],
            ['state_id' => 8, 'name' => 'Rohtak'],
            ['state_id' => 8, 'name' => 'Sirsa'],
            ['state_id' => 8, 'name' => 'Sonipat'],
            ['state_id' => 8, 'name' => 'Yamunanagar'],

            // Himachal Pradesh (state_id: 9)
            ['state_id' => 9, 'name' => 'Bilaspur'],
            ['state_id' => 9, 'name' => 'Chamba'],
            ['state_id' => 9, 'name' => 'Hamirpur'],
            ['state_id' => 9, 'name' => 'Kangra'],
            ['state_id' => 9, 'name' => 'Kinnaur'],
            ['state_id' => 9, 'name' => 'Kullu'],
            ['state_id' => 9, 'name' => 'Lahaul and Spiti'],
            ['state_id' => 9, 'name' => 'Mandi'],
            ['state_id' => 9, 'name' => 'Shimla'],
            ['state_id' => 9, 'name' => 'Sirmaur'],
            ['state_id' => 9, 'name' => 'Solan'],
            ['state_id' => 9, 'name' => 'Una'],

            // Jharkhand (state_id: 10)
            ['state_id' => 10, 'name' => 'Bokaro'],
            ['state_id' => 10, 'name' => 'Chatra'],
            ['state_id' => 10, 'name' => 'Deoghar'],
            ['state_id' => 10, 'name' => 'Dhanbad'],
            ['state_id' => 10, 'name' => 'Dumka'],
            ['state_id' => 10, 'name' => 'East Singhbhum'],
            ['state_id' => 10, 'name' => 'Garhwa'],
            ['state_id' => 10, 'name' => 'Giridih'],
            ['state_id' => 10, 'name' => 'Godda'],
            ['state_id' => 10, 'name' => 'Gumla'],
            ['state_id' => 10, 'name' => 'Hazaribagh'],
            ['state_id' => 10, 'name' => 'Jamtara'],
            ['state_id' => 10, 'name' => 'Khunti'],
            ['state_id' => 10, 'name' => 'Koderma'],
            ['state_id' => 10, 'name' => 'Latehar'],
            ['state_id' => 10, 'name' => 'Lohardaga'],
            ['state_id' => 10, 'name' => 'Pakur'],
            ['state_id' => 10, 'name' => 'Palamu'],
            ['state_id' => 10, 'name' => 'Ramgarh'],
            ['state_id' => 10, 'name' => 'Ranchi'],
            ['state_id' => 10, 'name' => 'Sahebganj'],
            ['state_id' => 10, 'name' => 'Seraikela Kharsawan'],
            ['state_id' => 10, 'name' => 'Simdega'],
            ['state_id' => 10, 'name' => 'West Singhbhum'],

            // Karnataka (state_id: 11)
            ['state_id' => 11, 'name' => 'Bagalkot'],
            ['state_id' => 11, 'name' => 'Ballari'],
            ['state_id' => 11, 'name' => 'Belagavi'],
            ['state_id' => 11, 'name' => 'Bengaluru Rural'],
            ['state_id' => 11, 'name' => 'Bengaluru Urban'],
            ['state_id' => 11, 'name' => 'Bidar'],
            ['state_id' => 11, 'name' => 'Chamarajanagar'],
            ['state_id' => 11, 'name' => 'Chikballapur'],
            ['state_id' => 11, 'name' => 'Chikkamagaluru'],
            ['state_id' => 11, 'name' => 'Chitradurga'],
            ['state_id' => 11, 'name' => 'Dakshina Kannada'],
            ['state_id' => 11, 'name' => 'Davanagere'],
            ['state_id' => 11, 'name' => 'Dharwad'],
            ['state_id' => 11, 'name' => 'Gadag'],
            ['state_id' => 11, 'name' => 'Hassan'],
            ['state_id' => 11, 'name' => 'Haveri'],
            ['state_id' => 11, 'name' => 'Kalaburagi'],
            ['state_id' => 11, 'name' => 'Kodagu'],
            ['state_id' => 11, 'name' => 'Kolar'],
            ['state_id' => 11, 'name' => 'Koppal'],
            ['state_id' => 11, 'name' => 'Mandya'],
            ['state_id' => 11, 'name' => 'Mysuru'],
            ['state_id' => 11, 'name' => 'Raichur'],
            ['state_id' => 11, 'name' => 'Ramanagara'],
            ['state_id' => 11, 'name' => 'Shivamogga'],
            ['state_id' => 11, 'name' => 'Tumakuru'],
            ['state_id' => 11, 'name' => 'Udupi'],
            ['state_id' => 11, 'name' => 'Uttara Kannada'],
            ['state_id' => 11, 'name' => 'Vijayapura'],
            ['state_id' => 11, 'name' => 'Yadgir'],

            // Kerala (state_id: 12)
            ['state_id' => 12, 'name' => 'Alappuzha'],
            ['state_id' => 12, 'name' => 'Ernakulam'],
            ['state_id' => 12, 'name' => 'Idukki'],
            ['state_id' => 12, 'name' => 'Kannur'],
            ['state_id' => 12, 'name' => 'Kasaragod'],
            ['state_id' => 12, 'name' => 'Kollam'],
            ['state_id' => 12, 'name' => 'Kottayam'],
            ['state_id' => 12, 'name' => 'Kozhikode'],
            ['state_id' => 12, 'name' => 'Malappuram'],
            ['state_id' => 12, 'name' => 'Palakkad'],
            ['state_id' => 12, 'name' => 'Pathanamthitta'],
            ['state_id' => 12, 'name' => 'Thiruvananthapuram'],
            ['state_id' => 12, 'name' => 'Thrissur'],
            ['state_id' => 12, 'name' => 'Wayanad'],

            // Madhya Pradesh (state_id: 13)
            ['state_id' => 13, 'name' => 'Agar Malwa'],
            ['state_id' => 13, 'name' => 'Alirajpur'],
            ['state_id' => 13, 'name' => 'Anuppur'],
            ['state_id' => 13, 'name' => 'Ashoknagar'],
            ['state_id' => 13, 'name' => 'Balaghat'],
            ['state_id' => 13, 'name' => 'Barwani'],
            ['state_id' => 13, 'name' => 'Betul'],
            ['state_id' => 13, 'name' => 'Bhind'],
            ['state_id' => 13, 'name' => 'Bhopal'],
            ['state_id' => 13, 'name' => 'Burhanpur'],
            ['state_id' => 13, 'name' => 'Chhatarpur'],
            ['state_id' => 13, 'name' => 'Chhindwara'],
            ['state_id' => 13, 'name' => 'Damoh'],
            ['state_id' => 13, 'name' => 'Datia'],
            ['state_id' => 13, 'name' => 'Dewas'],
            ['state_id' => 13, 'name' => 'Dhar'],
            ['state_id' => 13, 'name' => 'Dindori'],
            ['state_id' => 13, 'name' => 'Guna'],
            ['state_id' => 13, 'name' => 'Gwalior'],
            ['state_id' => 13, 'name' => 'Harda'],
            ['state_id' => 13, 'name' => 'Hoshangabad'],
            ['state_id' => 13, 'name' => 'Indore'],
            ['state_id' => 13, 'name' => 'Jabalpur'],
            ['state_id' => 13, 'name' => 'Jhabua'],
            ['state_id' => 13, 'name' => 'Katni'],
            ['state_id' => 13, 'name' => 'Khandwa'],
            ['state_id' => 13, 'name' => 'Khargone'],
            ['state_id' => 13, 'name' => 'Mandla'],
            ['state_id' => 13, 'name' => 'Mandsaur'],
            ['state_id' => 13, 'name' => 'Morena'],
            ['state_id' => 13, 'name' => 'Narsinghpur'],
            ['state_id' => 13, 'name' => 'Neemuch'],
            ['state_id' => 13, 'name' => 'Niwari'],
            ['state_id' => 13, 'name' => 'Panna'],
            ['state_id' => 13, 'name' => 'Raisen'],
            ['state_id' => 13, 'name' => 'Rajgarh'],
            ['state_id' => 13, 'name' => 'Ratlam'],
            ['state_id' => 13, 'name' => 'Rewa'],
            ['state_id' => 13, 'name' => 'Sagar'],
            ['state_id' => 13, 'name' => 'Satna'],
            ['state_id' => 13, 'name' => 'Sehore'],
            ['state_id' => 13, 'name' => 'Seoni'],
            ['state_id' => 13, 'name' => 'Shahdol'],
            ['state_id' => 13, 'name' => 'Shajapur'],
            ['state_id' => 13, 'name' => 'Sheopur'],
            ['state_id' => 13, 'name' => 'Shivpuri'],
            ['state_id' => 13, 'name' => 'Sidhi'],
            ['state_id' => 13, 'name' => 'Singrauli'],
            ['state_id' => 13, 'name' => 'Tikamgarh'],
            ['state_id' => 13, 'name' => 'Ujjain'],
            ['state_id' => 13, 'name' => 'Umaria'],
            ['state_id' => 13, 'name' => 'Vidisha'],

            // Maharashtra (state_id: 14)
            ['state_id' => 14, 'name' => 'Ahmednagar'],
            ['state_id' => 14, 'name' => 'Akola'],
            ['state_id' => 14, 'name' => 'Amravati'],
            ['state_id' => 14, 'name' => 'Aurangabad'],
            ['state_id' => 14, 'name' => 'Beed'],
            ['state_id' => 14, 'name' => 'Bhandara'],
            ['state_id' => 14, 'name' => 'Buldhana'],
            ['state_id' => 14, 'name' => 'Chandrapur'],
            ['state_id' => 14, 'name' => 'Dhule'],
            ['state_id' => 14, 'name' => 'Gadchiroli'],
            ['state_id' => 14, 'name' => 'Gondia'],
            ['state_id' => 14, 'name' => 'Hingoli'],
            ['state_id' => 14, 'name' => 'Jalgaon'],
            ['state_id' => 14, 'name' => 'Jalna'],
            ['state_id' => 14, 'name' => 'Kolhapur'],
            ['state_id' => 14, 'name' => 'Latur'],
            ['state_id' => 14, 'name' => 'Mumbai City'],
            ['state_id' => 14, 'name' => 'Mumbai Suburban'],
            ['state_id' => 14, 'name' => 'Nagpur'],
            ['state_id' => 14, 'name' => 'Nanded'],
            ['state_id' => 14, 'name' => 'Nandurbar'],
            ['state_id' => 14, 'name' => 'Nashik'],
            ['state_id' => 14, 'name' => 'Osmanabad'],
            ['state_id' => 14, 'name' => 'Palghar'],
            ['state_id' => 14, 'name' => 'Parbhani'],
            ['state_id' => 14, 'name' => 'Pune'],
            ['state_id' => 14, 'name' => 'Raigad'],
            ['state_id' => 14, 'name' => 'Ratnagiri'],
            ['state_id' => 14, 'name' => 'Sangli'],
            ['state_id' => 14, 'name' => 'Satara'],
            ['state_id' => 14, 'name' => 'Sindhudurg'],
            ['state_id' => 14, 'name' => 'Solapur'],
            ['state_id' => 14, 'name' => 'Thane'],
            ['state_id' => 14, 'name' => 'Wardha'],
            ['state_id' => 14, 'name' => 'Washim'],
            ['state_id' => 14, 'name' => 'Yavatmal'],

            // Manipur (state_id: 15)
            ['state_id' => 15, 'name' => 'Bishnupur'],
            ['state_id' => 15, 'name' => 'Chandel'],
            ['state_id' => 15, 'name' => 'Churachandpur'],
            ['state_id' => 15, 'name' => 'Imphal East'],
            ['state_id' => 15, 'name' => 'Imphal West'],
            ['state_id' => 15, 'name' => 'Jiribam'],
            ['state_id' => 15, 'name' => 'Kakching'],
            ['state_id' => 15, 'name' => 'Kamjong'],
            ['state_id' => 15, 'name' => 'Kangpokpi'],
            ['state_id' => 15, 'name' => 'Noney'],
            ['state_id' => 15, 'name' => 'Pherzawl'],
            ['state_id' => 15, 'name' => 'Senapati'],
            ['state_id' => 15, 'name' => 'Tamenglong'],
            ['state_id' => 15, 'name' => 'Tengnoupal'],
            ['state_id' => 15, 'name' => 'Thoubal'],
            ['state_id' => 15, 'name' => 'Ukhrul'],

            // Meghalaya (state_id: 16)
            ['state_id' => 16, 'name' => 'East Garo Hills'],
            ['state_id' => 16, 'name' => 'East Jaintia Hills'],
            ['state_id' => 16, 'name' => 'East Khasi Hills'],
            ['state_id' => 16, 'name' => 'North Garo Hills'],
            ['state_id' => 16, 'name' => 'Ri Bhoi'],
            ['state_id' => 16, 'name' => 'South Garo Hills'],
            ['state_id' => 16, 'name' => 'South West Garo Hills'],
            ['state_id' => 16, 'name' => 'South West Khasi Hills'],
            ['state_id' => 16, 'name' => 'West Garo Hills'],
            ['state_id' => 16, 'name' => 'West Jaintia Hills'],
            ['state_id' => 16, 'name' => 'West Khasi Hills'],

            // Mizoram (state_id: 17)
            ['state_id' => 17, 'name' => 'Aizawl'],
            ['state_id' => 17, 'name' => 'Champhai'],
            ['state_id' => 17, 'name' => 'Hnahthial'],
            ['state_id' => 17, 'name' => 'Khawzawl'],
            ['state_id' => 17, 'name' => 'Kolasib'],
            ['state_id' => 17, 'name' => 'Lawngtlai'],
            ['state_id' => 17, 'name' => 'Lunglei'],
            ['state_id' => 17, 'name' => 'Mamit'],
            ['state_id' => 17, 'name' => 'Saiha'],
            ['state_id' => 17, 'name' => 'Saitual'],
            ['state_id' => 17, 'name' => 'Serchhip'],

            // Nagaland (state_id: 18)
            ['state_id' => 18, 'name' => 'Dimapur'],
            ['state_id' => 18, 'name' => 'Kiphire'],
            ['state_id' => 18, 'name' => 'Kohima'],
            ['state_id' => 18, 'name' => 'Longleng'],
            ['state_id' => 18, 'name' => 'Mokokchung'],
            ['state_id' => 18, 'name' => 'Mon'],
            ['state_id' => 18, 'name' => 'Peren'],
            ['state_id' => 18, 'name' => 'Phek'],
            ['state_id' => 18, 'name' => 'Tuensang'],
            ['state_id' => 18, 'name' => 'Wokha'],
            ['state_id' => 18, 'name' => 'Zunheboto'],

            // Odisha (state_id: 19)
            ['state_id' => 19, 'name' => 'Angul'],
            ['state_id' => 19, 'name' => 'Balangir'],
            ['state_id' => 19, 'name' => 'Balasore'],
            ['state_id' => 19, 'name' => 'Bargarh'],
            ['state_id' => 19, 'name' => 'Bhadrak'],
            ['state_id' => 19, 'name' => 'Boudh'],
            ['state_id' => 19, 'name' => 'Cuttack'],
            ['state_id' => 19, 'name' => 'Deogarh'],
            ['state_id' => 19, 'name' => 'Dhenkanal'],
            ['state_id' => 19, 'name' => 'Gajapati'],
            ['state_id' => 19, 'name' => 'Ganjam'],
            ['state_id' => 19, 'name' => 'Jagatsinghpur'],
            ['state_id' => 19, 'name' => 'Jajpur'],
            ['state_id' => 19, 'name' => 'Jharsuguda'],
            ['state_id' => 19, 'name' => 'Kalahandi'],
            ['state_id' => 19, 'name' => 'Kandhamal'],
            ['state_id' => 19, 'name' => 'Kendrapara'],
            ['state_id' => 19, 'name' => 'Kendujhar'],
            ['state_id' => 19, 'name' => 'Khordha'],
            ['state_id' => 19, 'name' => 'Koraput'],
            ['state_id' => 19, 'name' => 'Malkangiri'],
            ['state_id' => 19, 'name' => 'Mayurbhanj'],
            ['state_id' => 19, 'name' => 'Nabarangpur'],
            ['state_id' => 19, 'name' => 'Nayagarh'],
            ['state_id' => 19, 'name' => 'Nuapada'],
            ['state_id' => 19, 'name' => 'Puri'],
            ['state_id' => 19, 'name' => 'Rayagada'],
            ['state_id' => 19, 'name' => 'Sambalpur'],
            ['state_id' => 19, 'name' => 'Subarnapur'],
            ['state_id' => 19, 'name' => 'Sundargarh'],

            // Punjab (state_id: 20)
            ['state_id' => 20, 'name' => 'Amritsar'],
            ['state_id' => 20, 'name' => 'Barnala'],
            ['state_id' => 20, 'name' => 'Bathinda'],
            ['state_id' => 20, 'name' => 'Faridkot'],
            ['state_id' => 20, 'name' => 'Fatehgarh Sahib'],
            ['state_id' => 20, 'name' => 'Fazilka'],
            ['state_id' => 20, 'name' => 'Ferozepur'],
            ['state_id' => 20, 'name' => 'Gurdaspur'],
            ['state_id' => 20, 'name' => 'Hoshiarpur'],
            ['state_id' => 20, 'name' => 'Jalandhar'],
            ['state_id' => 20, 'name' => 'Kapurthala'],
            ['state_id' => 20, 'name' => 'Ludhiana'],
            ['state_id' => 20, 'name' => 'Mansa'],
            ['state_id' => 20, 'name' => 'Moga'],
            ['state_id' => 20, 'name' => 'Muktsar'],
            ['state_id' => 20, 'name' => 'Nawanshahr'],
            ['state_id' => 20, 'name' => 'Pathankot'],
            ['state_id' => 20, 'name' => 'Patiala'],
            ['state_id' => 20, 'name' => 'Rupnagar'],
            ['state_id' => 20, 'name' => 'Sangrur'],
            ['state_id' => 20, 'name' => 'Tarn Taran'],

            // Rajasthan (state_id: 21)
            ['state_id' => 21, 'name' => 'Ajmer'],
            ['state_id' => 21, 'name' => 'Alwar'],
            ['state_id' => 21, 'name' => 'Banswara'],
            ['state_id' => 21, 'name' => 'Baran'],
            ['state_id' => 21, 'name' => 'Barmer'],
            ['state_id' => 21, 'name' => 'Bharatpur'],
            ['state_id' => 21, 'name' => 'Bhilwara'],
            ['state_id' => 21, 'name' => 'Bikaner'],
            ['state_id' => 21, 'name' => 'Bundi'],
            ['state_id' => 21, 'name' => 'Chittorgarh'],
            ['state_id' => 21, 'name' => 'Churu'],
            ['state_id' => 21, 'name' => 'Dausa'],
            ['state_id' => 21, 'name' => 'Dholpur'],
            ['state_id' => 21, 'name' => 'Dungarpur'],
            ['state_id' => 21, 'name' => 'Hanumangarh'],
            ['state_id' => 21, 'name' => 'Jaipur'],
            ['state_id' => 21, 'name' => 'Jaisalmer'],
            ['state_id' => 21, 'name' => 'Jalore'],
            ['state_id' => 21, 'name' => 'Jhalawar'],
            ['state_id' => 21, 'name' => 'Jhunjhunu'],
            ['state_id' => 21, 'name' => 'Jodhpur'],
            ['state_id' => 21, 'name' => 'Karauli'],
            ['state_id' => 21, 'name' => 'Kota'],
            ['state_id' => 21, 'name' => 'Nagaur'],
            ['state_id' => 21, 'name' => 'Pali'],
            ['state_id' => 21, 'name' => 'Pratapgarh'],
            ['state_id' => 21, 'name' => 'Rajsamand'],
            ['state_id' => 21, 'name' => 'Sawai Madhopur'],
            ['state_id' => 21, 'name' => 'Sikar'],
            ['state_id' => 21, 'name' => 'Sirohi'],
            ['state_id' => 21, 'name' => 'Sri Ganganagar'],
            ['state_id' => 21, 'name' => 'Tonk'],
            ['state_id' => 21, 'name' => 'Udaipur'],

            // Sikkim (state_id: 22)
            ['state_id' => 22, 'name' => 'East Sikkim'],
            ['state_id' => 22, 'name' => 'North Sikkim'],
            ['state_id' => 22, 'name' => 'South Sikkim'],
            ['state_id' => 22, 'name' => 'West Sikkim'],

            // Tamil Nadu (state_id: 23)
            ['state_id' => 23, 'name' => 'Ariyalur'],
            ['state_id' => 23, 'name' => 'Chengalpattu'],
            ['state_id' => 23, 'name' => 'Chennai'],
            ['state_id' => 23, 'name' => 'Coimbatore'],
            ['state_id' => 23, 'name' => 'Cuddalore'],
            ['state_id' => 23, 'name' => 'Dharmapuri'],
            ['state_id' => 23, 'name' => 'Dindigul'],
            ['state_id' => 23, 'name' => 'Erode'],
            ['state_id' => 23, 'name' => 'Kallakurichi'],
            ['state_id' => 23, 'name' => 'Kanchipuram'],
            ['state_id' => 23, 'name' => 'Kanyakumari'],
            ['state_id' => 23, 'name' => 'Karur'],
            ['state_id' => 23, 'name' => 'Krishnagiri'],
            ['state_id' => 23, 'name' => 'Madurai'],
            ['state_id' => 23, 'name' => 'Mayiladuthurai'],
            ['state_id' => 23, 'name' => 'Nagapattinam'],
            ['state_id' => 23, 'name' => 'Namakkal'],
            ['state_id' => 23, 'name' => 'Nilgiris'],
            ['state_id' => 23, 'name' => 'Perambalur'],
            ['state_id' => 23, 'name' => 'Pudukkottai'],
            ['state_id' => 23, 'name' => 'Ramanathapuram'],
            ['state_id' => 23, 'name' => 'Ranipet'],
            ['state_id' => 23, 'name' => 'Salem'],
            ['state_id' => 23, 'name' => 'Sivaganga'],
            ['state_id' => 23, 'name' => 'Tenkasi'],
            ['state_id' => 23, 'name' => 'Thanjavur'],
            ['state_id' => 23, 'name' => 'Theni'],
            ['state_id' => 23, 'name' => 'Thoothukudi'],
            ['state_id' => 23, 'name' => 'Tiruchirappalli'],
            ['state_id' => 23, 'name' => 'Tirunelveli'],
            ['state_id' => 23, 'name' => 'Tirupattur'],
            ['state_id' => 23, 'name' => 'Tiruppur'],
            ['state_id' => 23, 'name' => 'Tiruvallur'],
            ['state_id' => 23, 'name' => 'Tiruvannamalai'],
            ['state_id' => 23, 'name' => 'Tiruvarur'],
            ['state_id' => 23, 'name' => 'Vellore'],
            ['state_id' => 23, 'name' => 'Viluppuram'],
            ['state_id' => 23, 'name' => 'Virudhunagar'],

            // Telangana (state_id: 24)
            ['state_id' => 24, 'name' => 'Adilabad'],
            ['state_id' => 24, 'name' => 'Bhadradri Kothagudem'],
            ['state_id' => 24, 'name' => 'Hyderabad'],
            ['state_id' => 24, 'name' => 'Jagtial'],
            ['state_id' => 24, 'name' => 'Jangaon'],
            ['state_id' => 24, 'name' => 'Jayashankar Bhupalpally'],
            ['state_id' => 24, 'name' => 'Jogulamba Gadwal'],
            ['state_id' => 24, 'name' => 'Kamareddy'],
            ['state_id' => 24, 'name' => 'Karimnagar'],
            ['state_id' => 24, 'name' => 'Khammam'],
            ['state_id' => 24, 'name' => 'Komaram Bheem Asifabad'],
            ['state_id' => 24, 'name' => 'Mahabubabad'],
            ['state_id' => 24, 'name' => 'Mahabubnagar'],
            ['state_id' => 24, 'name' => 'Mancherial'],
            ['state_id' => 24, 'name' => 'Medak'],
            ['state_id' => 24, 'name' => 'Medchal Malkajgiri'],
            ['state_id' => 24, 'name' => 'Mulugu'],
            ['state_id' => 24, 'name' => 'Nagarkurnool'],
            ['state_id' => 24, 'name' => 'Nalgonda'],
            ['state_id' => 24, 'name' => 'Narayanpet'],
            ['state_id' => 24, 'name' => 'Nirmal'],
            ['state_id' => 24, 'name' => 'Nizamabad'],
            ['state_id' => 24, 'name' => 'Peddapalli'],
            ['state_id' => 24, 'name' => 'Rajanna Sircilla'],
            ['state_id' => 24, 'name' => 'Ranga Reddy'],
            ['state_id' => 24, 'name' => 'Sangareddy'],
            ['state_id' => 24, 'name' => 'Siddipet'],
            ['state_id' => 24, 'name' => 'Suryapet'],
            ['state_id' => 24, 'name' => 'Vikarabad'],
            ['state_id' => 24, 'name' => 'Wanaparthy'],
            ['state_id' => 24, 'name' => 'Warangal Rural'],
            ['state_id' => 24, 'name' => 'Warangal Urban'],
            ['state_id' => 24, 'name' => 'Yadadri Bhuvanagiri'],

            // Tripura (state_id: 25)
            ['state_id' => 25, 'name' => 'Dhalai'],
            ['state_id' => 25, 'name' => 'Gomati'],
            ['state_id' => 25, 'name' => 'Khowai'],
            ['state_id' => 25, 'name' => 'North Tripura'],
            ['state_id' => 25, 'name' => 'Sepahijala'],
            ['state_id' => 25, 'name' => 'South Tripura'],
            ['state_id' => 25, 'name' => 'Unakoti'],
            ['state_id' => 25, 'name' => 'West Tripura'],

            // Uttar Pradesh (state_id: 26)
            ['state_id' => 26, 'name' => 'Agra'],
            ['state_id' => 26, 'name' => 'Aligarh'],
            ['state_id' => 26, 'name' => 'Ambedkar Nagar'],
            ['state_id' => 26, 'name' => 'Amethi'],
            ['state_id' => 26, 'name' => 'Amroha'],
            ['state_id' => 26, 'name' => 'Auraiya'],
            ['state_id' => 26, 'name' => 'Azamgarh'],
            ['state_id' => 26, 'name' => 'Baghpat'],
            ['state_id' => 26, 'name' => 'Bahraich'],
            ['state_id' => 26, 'name' => 'Ballia'],
            ['state_id' => 26, 'name' => 'Balrampur'],
            ['state_id' => 26, 'name' => 'Banda'],
            ['state_id' => 26, 'name' => 'Barabanki'],
            ['state_id' => 26, 'name' => 'Bareilly'],
            ['state_id' => 26, 'name' => 'Basti'],
            ['state_id' => 26, 'name' => 'Bhadohi'],
            ['state_id' => 26, 'name' => 'Bijnor'],
            ['state_id' => 26, 'name' => 'Budaun'],
            ['state_id' => 26, 'name' => 'Bulandshahr'],
            ['state_id' => 26, 'name' => 'Chandauli'],
            ['state_id' => 26, 'name' => 'Chitrakoot'],
            ['state_id' => 26, 'name' => 'Deoria'],
            ['state_id' => 26, 'name' => 'Etah'],
            ['state_id' => 26, 'name' => 'Etawah'],
            ['state_id' => 26, 'name' => 'Faizabad'],
            ['state_id' => 26, 'name' => 'Farrukhabad'],
            ['state_id' => 26, 'name' => 'Fatehpur'],
            ['state_id' => 26, 'name' => 'Firozabad'],
            ['state_id' => 26, 'name' => 'Gautam Buddha Nagar'],
            ['state_id' => 26, 'name' => 'Ghaziabad'],
            ['state_id' => 26, 'name' => 'Ghazipur'],
            ['state_id' => 26, 'name' => 'Gonda'],
            ['state_id' => 26, 'name' => 'Gorakhpur'],
            ['state_id' => 26, 'name' => 'Hamirpur'],
            ['state_id' => 26, 'name' => 'Hapur'],
            ['state_id' => 26, 'name' => 'Hardoi'],
            ['state_id' => 26, 'name' => 'Hathras'],
            ['state_id' => 26, 'name' => 'Jalaun'],
            ['state_id' => 26, 'name' => 'Jaunpur'],
            ['state_id' => 26, 'name' => 'Jhansi'],
            ['state_id' => 26, 'name' => 'Kannauj'],
            ['state_id' => 26, 'name' => 'Kanpur Dehat'],
            ['state_id' => 26, 'name' => 'Kanpur Nagar'],
            ['state_id' => 26, 'name' => 'Kasganj'],
            ['state_id' => 26, 'name' => 'Kaushambi'],
            ['state_id' => 26, 'name' => 'Kheri'],
            ['state_id' => 26, 'name' => 'Kushinagar'],
            ['state_id' => 26, 'name' => 'Lalitpur'],
            ['state_id' => 26, 'name' => 'Lucknow'],
            ['state_id' => 26, 'name' => 'Maharajganj'],
            ['state_id' => 26, 'name' => 'Mahoba'],
            ['state_id' => 26, 'name' => 'Mainpuri'],
            ['state_id' => 26, 'name' => 'Mathura'],
            ['state_id' => 26, 'name' => 'Mau'],
            ['state_id' => 26, 'name' => 'Meerut'],
            ['state_id' => 26, 'name' => 'Mirzapur'],
            ['state_id' => 26, 'name' => 'Moradabad'],
            ['state_id' => 26, 'name' => 'Muzaffarnagar'],
            ['state_id' => 26, 'name' => 'Pilibhit'],
            ['state_id' => 26, 'name' => 'Pratapgarh'],
            ['state_id' => 26, 'name' => 'Prayagraj'],
            ['state_id' => 26, 'name' => 'Raebareli'],
            ['state_id' => 26, 'name' => 'Rampur'],
            ['state_id' => 26, 'name' => 'Saharanpur'],
            ['state_id' => 26, 'name' => 'Sambhal'],
            ['state_id' => 26, 'name' => 'Sant Kabir Nagar'],
            ['state_id' => 26, 'name' => 'Shahjahanpur'],
            ['state_id' => 26, 'name' => 'Shamli'],
            ['state_id' => 26, 'name' => 'Shrawasti'],
            ['state_id' => 26, 'name' => 'Siddharthnagar'],
            ['state_id' => 26, 'name' => 'Sitapur'],
            ['state_id' => 26, 'name' => 'Sonbhadra'],
            ['state_id' => 26, 'name' => 'Sultanpur'],
            ['state_id' => 26, 'name' => 'Unnao'],
            ['state_id' => 26, 'name' => 'Varanasi'],

            // Uttarakhand (state_id: 27)
            ['state_id' => 27, 'name' => 'Almora'],
            ['state_id' => 27, 'name' => 'Bageshwar'],
            ['state_id' => 27, 'name' => 'Chamoli'],
            ['state_id' => 27, 'name' => 'Champawat'],
            ['state_id' => 27, 'name' => 'Dehradun'],
            ['state_id' => 27, 'name' => 'Haridwar'],
            ['state_id' => 27, 'name' => 'Nainital'],
            ['state_id' => 27, 'name' => 'Pauri Garhwal'],
            ['state_id' => 27, 'name' => 'Pithoragarh'],
            ['state_id' => 27, 'name' => 'Rudraprayag'],
            ['state_id' => 27, 'name' => 'Tehri Garhwal'],
            ['state_id' => 27, 'name' => 'Udham Singh Nagar'],
            ['state_id' => 27, 'name' => 'Uttarkashi'],

            // West Bengal (state_id: 28)
            ['state_id' => 28, 'name' => 'Alipurduar'],
            ['state_id' => 28, 'name' => 'Bankura'],
            ['state_id' => 28, 'name' => 'Birbhum'],
            ['state_id' => 28, 'name' => 'Cooch Behar'],
            ['state_id' => 28, 'name' => 'Dakshin Dinajpur'],
            ['state_id' => 28, 'name' => 'Darjeeling'],
            ['state_id' => 28, 'name' => 'Hooghly'],
            ['state_id' => 28, 'name' => 'Howrah'],
            ['state_id' => 28, 'name' => 'Jalpaiguri'],
            ['state_id' => 28, 'name' => 'Jhargram'],
            ['state_id' => 28, 'name' => 'Kalimpong'],
            ['state_id' => 28, 'name' => 'Kolkata'],
            ['state_id' => 28, 'name' => 'Malda'],
            ['state_id' => 28, 'name' => 'Murshidabad'],
            ['state_id' => 28, 'name' => 'Nadia'],
            ['state_id' => 28, 'name' => 'North 24 Parganas'],
            ['state_id' => 28, 'name' => 'Paschim Bardhaman'],
            ['state_id' => 28, 'name' => 'Paschim Medinipur'],
            ['state_id' => 28, 'name' => 'Purba Bardhaman'],
            ['state_id' => 28, 'name' => 'Purba Medinipur'],
            ['state_id' => 28, 'name' => 'Purulia'],
            ['state_id' => 28, 'name' => 'South 24 Parganas'],
            ['state_id' => 28, 'name' => 'Uttar Dinajpur'],

            // Delhi (state_id: 29)
            ['state_id' => 29, 'name' => 'Central Delhi'],
            ['state_id' => 29, 'name' => 'East Delhi'],
            ['state_id' => 29, 'name' => 'New Delhi'],
            ['state_id' => 29, 'name' => 'North Delhi'],
            ['state_id' => 29, 'name' => 'North East Delhi'],
            ['state_id' => 29, 'name' => 'North West Delhi'],
            ['state_id' => 29, 'name' => 'Shahdara'],
            ['state_id' => 29, 'name' => 'South Delhi'],
            ['state_id' => 29, 'name' => 'South East Delhi'],
            ['state_id' => 29, 'name' => 'South West Delhi'],
            ['state_id' => 29, 'name' => 'West Delhi'],

            // Jammu and Kashmir (state_id: 30)
            ['state_id' => 30, 'name' => 'Anantnag'],
            ['state_id' => 30, 'name' => 'Bandipora'],
            ['state_id' => 30, 'name' => 'Baramulla'],
            ['state_id' => 30, 'name' => 'Budgam'],
            ['state_id' => 30, 'name' => 'Doda'],
            ['state_id' => 30, 'name' => 'Ganderbal'],
            ['state_id' => 30, 'name' => 'Jammu'],
            ['state_id' => 30, 'name' => 'Kathua'],
            ['state_id' => 30, 'name' => 'Kishtwar'],
            ['state_id' => 30, 'name' => 'Kulgam'],
            ['state_id' => 30, 'name' => 'Kupwara'],
            ['state_id' => 30, 'name' => 'Poonch'],
            ['state_id' => 30, 'name' => 'Pulwama'],
            ['state_id' => 30, 'name' => 'Rajouri'],
            ['state_id' => 30, 'name' => 'Ramban'],
            ['state_id' => 30, 'name' => 'Reasi'],
            ['state_id' => 30, 'name' => 'Samba'],
            ['state_id' => 30, 'name' => 'Shopian'],
            ['state_id' => 30, 'name' => 'Srinagar'],
            ['state_id' => 30, 'name' => 'Udhampur'],

            // Ladakh (state_id: 31)
            ['state_id' => 31, 'name' => 'Kargil'],
            ['state_id' => 31, 'name' => 'Leh'],

            // Puducherry (state_id: 32)
            ['state_id' => 32, 'name' => 'Karaikal'],
            ['state_id' => 32, 'name' => 'Mahe'],
            ['state_id' => 32, 'name' => 'Puducherry'],
            ['state_id' => 32, 'name' => 'Yanam'],

            // Chandigarh (state_id: 33)
            ['state_id' => 33, 'name' => 'Chandigarh'],

            // Dadra and Nagar Haveli and Daman and Diu (state_id: 34)
            ['state_id' => 34, 'name' => 'Dadra and Nagar Haveli'],
            ['state_id' => 34, 'name' => 'Daman'],
            ['state_id' => 34, 'name' => 'Diu'],

            // Lakshadweep (state_id: 35)
            ['state_id' => 35, 'name' => 'Agatti'],
            ['state_id' => 35, 'name' => 'Amini'],
            ['state_id' => 35, 'name' => 'Androth'],
            ['state_id' => 35, 'name' => 'Bithra'],
            ['state_id' => 35, 'name' => 'Chetlath'],
            ['state_id' => 35, 'name' => 'Kadmath'],
            ['state_id' => 35, 'name' => 'Kalpeni'],
            ['state_id' => 35, 'name' => 'Kavaratti'],
            ['state_id' => 35, 'name' => 'Kiltan'],
            ['state_id' => 35, 'name' => 'Minicoy'],

            // Andaman and Nicobar Islands (state_id: 36)
            ['state_id' => 36, 'name' => 'Nicobar'],
            ['state_id' => 36, 'name' => 'North and Middle Andaman'],
            ['state_id' => 36, 'name' => 'South Andaman'],
        ];

        foreach ($lgas as $lga) {
            Lga::create($lga);
        }
    }
}
